name: Addon CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: Poeschl-HomeAssistant-Addons/workflows/.github/workflows/addon-ci.yaml@main
